import { Candidate, TimelineItem, User } from './types';

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 1,
    name: 'Bertolomeus Rowa',
    position: 'Scaffolder',
    status: 'Ditolak',
    hrResult: 'Lolos',
    userResult: 'Tidak Lolos',
    notes: 'Ijazah yang dilampirkan tidak sesuai',
    dateAdded: '2026-06-25',
    source: 'LinkedIn',
  },
  {
    id: 2,
    name: 'Wahyu Mujayadi',
    position: 'Scaffolder',
    status: 'Ditolak',
    hrResult: 'Lolos',
    userResult: '-',
    notes: 'Tidak sesuai kualifikasi',
    dateAdded: '2026-06-25',
    source: 'Jobstreet',
  },
  {
    id: 3,
    name: 'Julianda Toni Putra',
    position: 'Scaffolder',
    status: 'User Interview',
    hrResult: 'Dijadwalkan',
    userResult: 'Dijadwalkan',
    notes: '-',
    dateAdded: '2026-06-26',
    source: 'Website',
  },
  {
    id: 4,
    name: 'Bachruddin Muhammad Rivqy',
    position: 'Safety Officer',
    status: 'HR Interview',
    hrResult: 'No Show',
    userResult: 'No Show',
    notes: 'Tidak sesuai kualifikasi',
    dateAdded: '2026-06-26',
    source: 'LinkedIn',
  },
  {
    id: 5,
    name: 'Wahyu Adha Pradana',
    position: 'Safety Officer',
    status: 'Ditolak',
    hrResult: 'Lolos',
    userResult: 'Tidak Lolos',
    notes: 'Tidak Ada Keterangan',
    dateAdded: '2026-06-27',
    source: 'E-Mail',
  },
  {
    id: 8,
    name: 'Muhammad Gilang Ramdhani',
    position: 'Safety Officer',
    status: 'Medical Check',
    hrResult: 'Lolos',
    userResult: 'Lolos',
    notes: 'Potensial safety specialist',
    dateAdded: '2026-06-27',
    source: 'Google Form',
  },
  {
    id: 9,
    name: 'Hendrik Khusairi',
    position: 'Scaffolder',
    status: 'Medical Check',
    hrResult: 'Lolos',
    userResult: 'Lolos',
    notes: 'Kualifikasi teknis sangat baik',
    dateAdded: '2026-08-28',
    source: 'Referensi',
  },
  {
    id: 10,
    name: 'M. Fadillah',
    position: 'Safety Officer',
    status: 'Medical Check',
    hrResult: 'Lolos',
    userResult: 'Lolos',
    notes: 'Sertifikasi K3 Umum lengkap',
    dateAdded: '2026-06-28',
    source: 'LinkedIn',
  },
  {
    id: 11,
    name: 'Taufik',
    position: 'Rigger',
    status: 'Medical Check',
    hrResult: 'Lolos',
    userResult: 'Lolos',
    notes: 'Pengalaman rigger 5 tahun',
    dateAdded: '2026-06-28',
    source: 'Jobstreet',
  },
  {
    id: 12,
    name: 'Dani Setiawan',
    position: 'Welder',
    status: 'Pending',
    hrResult: 'Dijadwalkan',
    userResult: '-',
    notes: 'Sertifikat 6G MIG aktif',
    dateAdded: '2026-06-29',
    source: 'E-Mail',
  },
  {
    id: 13,
    name: 'Budi Santoso',
    position: 'Scaffolder',
    status: 'Ditolak',
    hrResult: 'Tidak Lolos',
    userResult: '-',
    notes: 'Pengalaman kerja kurang dari 1 tahun',
    dateAdded: '2026-06-29',
    source: 'Website',
  },
  {
    id: 14,
    name: 'Ahmad Subarjo',
    position: 'Crane Operator',
    status: 'User Interview',
    hrResult: 'Lolos',
    userResult: 'Dijadwalkan',
    notes: 'Sertifikasi SIO Kelas II',
    dateAdded: '2026-06-30',
    source: 'Google Form',
  },
  {
    id: 15,
    name: 'Rian Hidayat',
    position: 'Safety Inspector',
    status: 'User Interview',
    hrResult: 'Lolos',
    userResult: 'Dijadwalkan',
    notes: 'Mengerti HSE auditing',
    dateAdded: '2026-06-30',
    source: 'LinkedIn',
  },
  {
    id: 16,
    name: 'Supriadi',
    position: 'Rigger',
    status: 'Pending',
    hrResult: 'Lolos',
    userResult: 'Tidak Lolos',
    notes: 'Gagal tes beban rigger',
    dateAdded: '2026-07-01',
    source: 'Referensi',
  }
];

export const INITIAL_TIMELINE: TimelineItem[] = [
  {
    id: 't1',
    date: 'July 03',
    title: 'User Interview',
    description: 'Julianda Toni Putra scheduled',
  },
  {
    id: 't2',
    date: 'June 30',
    title: 'Medical Check',
    description: 'Hendrik Khusairi, M. Fadillah, Taufik',
  },
  {
    id: 't3',
    date: 'June 26',
    title: 'Pipeline Review',
    description: 'Completed daily tracking log update',
  }
];

export const MOCK_USER: User = {
  username: 'admin',
  email: 'Hilmiassidqi27@gmail.com',
  fullName: 'PIC Rekrutmen',
  role: 'Administrator',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBm_aO0EnDTBH5_fczgi5bqxnYJhuL7P3nG2FsUhMK07jZb-IuOD1QH4jY5q4v1Ba_Bg-5EZ7f77zU6Ap7HkfT3ccGN0RWiidC8IDjM0K738ddAJIuZLDO1iARw4EEPDEineYzvO7wlHl1unBJS7bY-M3Jw7RLX4mmqK5Pt2ntjcOOYUS-OcNfTJWNYfxwv824hBeusl_JfkJ8bqp1VhNOPmgJybKIsba87IuCWOUKBjbRCOj8bVjf5l4bylFync1nK4x4qZOEivkVs'
};

export const POSITIONS_LIST = [
  'Scaffolder',
  'Safety Officer',
  'Rigger',
  'Welder',
  'Crane Operator',
  'Safety Inspector'
];
